

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================




#include "ComponentInitializer.h"
#include "../../Manager/ComponentManager.h"
#include "strKey_Component.h"


#include "Audio\Com_AudioListener.h"
#include "Animator\Com_Animator2D.h"
#include "Light\Com_Light3D.h"
#include "Animator\Com_Animator3D.h"
#include "Renderer\Com_Renderer_3DAnimMesh.h"
#include "Camera\Com_Camera.h"
#include "Transform\Com_Transform.h"
#include "Audio\Com_AudioSource.h"
#include "Renderer\Com_Renderer_Mesh.h"
#include "Renderer\Com_Renderer_ParticleSystem.h"
#include "Renderer\Com_Renderer_Sprite.h"
#include "Renderer\Com_Renderer_UIBase.h"
#include "StateMachine\Com_BehaviorTree.h"

#define CONSTRUCTOR_T(T) ComponentManager::AddComponentConstructor<T>(strKey::component::##T)

namespace ehw
{

	void ComponentInitializer::Init()
	{
		CONSTRUCTOR_T(Com_AudioListener);
		CONSTRUCTOR_T(Com_Animator2D);
		CONSTRUCTOR_T(Com_Light3D);
		CONSTRUCTOR_T(Com_Animator3D);
		CONSTRUCTOR_T(Com_Renderer_3DAnimMesh);
		CONSTRUCTOR_T(Com_Camera);
		CONSTRUCTOR_T(Com_Transform);
		CONSTRUCTOR_T(Com_AudioSource);
		CONSTRUCTOR_T(Com_Renderer_Mesh);
		CONSTRUCTOR_T(Com_Renderer_ParticleSystem);
		CONSTRUCTOR_T(Com_Renderer_Sprite);
		CONSTRUCTOR_T(Com_Renderer_UIBase);
		CONSTRUCTOR_T(Com_BehaviorTree);
	}
}