
//=========================================================
//This Code is Automatically generated by CodeGenerator
//=========================================================


#include "Engine/PCH_Engine.h"
#include "Engine/Game/Component/ComponentInitializer.h"

#include "Engine/Manager/ComponentManager.h"
#include "Engine/Game/Component/iComponent.h"
#include "Engine/Game/Component/strKey_Component.h"

#include "Engine/Game/Component\Audio\Com_AudioListener.h"
#include "Engine/Game/Component\Animator\Com_Animator2D.h"
#include "Engine/Game/Component\Light\Com_Light3D.h"
#include "Engine/Game/Component\Animator\Com_Animator3D.h"
#include "Engine/Game/Component\Audio\Com_AudioSource.h"
#include "Engine/Game/Component\Renderer\Com_Renderer_3DAnimMesh.h"
#include "Engine/Game/Component\Camera\Com_Camera.h"
#include "Engine/Game/Component\Collider\Com_Collider2D_AABB.h"
#include "Engine/Game/Component\Renderer\Com_Renderer_Mesh.h"
#include "Engine/Game/Component\Renderer\Com_Renderer_ParticleSystem.h"
#include "Engine/Game/Component\Renderer\Com_Renderer_Sprite.h"
#include "Engine/Game/Component\Renderer\Com_Renderer_UIBase.h"
#include "Engine/Game/Component\StateMachine\Com_BehaviorTree.h"
#include "Engine/Game/Component\Transform\Com_Transform.h"

#define CONSTRUCTOR_T(T) ComponentManager::AddComponentConstructor<T>(strKey::component::##T)

namespace ehw
{
	void ComponentInitializer::Init()
	{
		CONSTRUCTOR_T(Com_AudioListener);
		CONSTRUCTOR_T(Com_Animator2D);
		CONSTRUCTOR_T(Com_Light3D);
		CONSTRUCTOR_T(Com_Animator3D);
		CONSTRUCTOR_T(Com_AudioSource);
		CONSTRUCTOR_T(Com_Renderer_3DAnimMesh);
		CONSTRUCTOR_T(Com_Camera);
		CONSTRUCTOR_T(Com_Collider2D_AABB);
		CONSTRUCTOR_T(Com_Renderer_Mesh);
		CONSTRUCTOR_T(Com_Renderer_ParticleSystem);
		CONSTRUCTOR_T(Com_Renderer_Sprite);
		CONSTRUCTOR_T(Com_Renderer_UIBase);
		CONSTRUCTOR_T(Com_BehaviorTree);
		CONSTRUCTOR_T(Com_Transform);
	}
}