
#pragma once

//=========================================================
//This Code is Automatically generated by CodeGenerator
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace ehw::strKey::component
{
	STRKEY Com_Animator2D = "Com_Animator2D";
	STRKEY Com_Animator3D = "Com_Animator3D";
	STRKEY Com_AudioListener = "Com_AudioListener";
	STRKEY Com_AudioSource = "Com_AudioSource";
	STRKEY Com_Camera = "Com_Camera";
	STRKEY Com_Collider2D_AABB = "Com_Collider2D_AABB";
	STRKEY Com_Collider3D_Capsule = "Com_Collider3D_Capsule";
	STRKEY Com_Collider3D_Cube = "Com_Collider3D_Cube";
	STRKEY Com_Collider3D_Rigid = "Com_Collider3D_Rigid";
	STRKEY Com_Collider3D_Sphere = "Com_Collider3D_Sphere";
	STRKEY Com_Light3D = "Com_Light3D";
	STRKEY Com_Renderer_3DAnimMesh = "Com_Renderer_3DAnimMesh";
	STRKEY Com_Renderer_Mesh = "Com_Renderer_Mesh";
	STRKEY Com_Renderer_ParticleSystem = "Com_Renderer_ParticleSystem";
	STRKEY Com_Renderer_Sprite = "Com_Renderer_Sprite";
	STRKEY Com_Renderer_UIBase = "Com_Renderer_UIBase";
	STRKEY Com_BehaviorTree = "Com_BehaviorTree";
	STRKEY Com_Transform = "Com_Transform";
}
