
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace ehw::strKey::component
{
	STRKEY Com_Animator3D = "Com_Animator3D";
	STRKEY Com_AudioListener = "Com_AudioListener";
	STRKEY Com_AudioSource = "Com_AudioSource";
	STRKEY Com_BehaviorTree = "Com_BehaviorTree";
	STRKEY Com_Camera = "Com_Camera";
	STRKEY Com_DummyAnimator = "Com_DummyAnimator";
	STRKEY Com_DummyTransform = "Com_DummyTransform";
	STRKEY Com_Light3D = "Com_Light3D";
	STRKEY Com_Renderer_3DAnimMesh = "Com_Renderer_3DAnimMesh";
	STRKEY Com_Renderer_Mesh = "Com_Renderer_Mesh";
	STRKEY Com_Renderer_ParticleSystem = "Com_Renderer_ParticleSystem";
	STRKEY Com_Renderer_Sprite = "Com_Renderer_Sprite";
	STRKEY Com_Renderer_UIBase = "Com_Renderer_UIBase";
	STRKEY Com_Transform = "Com_Transform";
	STRKEY Com_Animator2D = "Com_Animator2D";
}
